
package com.helloweb.webclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Webservicehello", targetNamespace = "http://ws.helloweb.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Webservicehello {


    /**
     * 
     * @param guestname
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.helloweb.com/Webservicehello/sayHelloRequest", output = "http://ws.helloweb.com/Webservicehello/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "guestname", partName = "guestname")
        String guestname);

}
