
package com.helloweb.webclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebservicehelloService", targetNamespace = "http://ws.helloweb.com/", wsdlLocation = "http://localhost:8888/HelloService/helloService?WSDL")
public class WebservicehelloService
    extends Service
{

    private final static URL WEBSERVICEHELLOSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEHELLOSERVICE_EXCEPTION;
    private final static QName WEBSERVICEHELLOSERVICE_QNAME = new QName("http://ws.helloweb.com/", "WebservicehelloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/HelloService/helloService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEHELLOSERVICE_WSDL_LOCATION = url;
        WEBSERVICEHELLOSERVICE_EXCEPTION = e;
    }

    public WebservicehelloService() {
        super(__getWsdlLocation(), WEBSERVICEHELLOSERVICE_QNAME);
    }

    public WebservicehelloService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEHELLOSERVICE_QNAME, features);
    }

    public WebservicehelloService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEHELLOSERVICE_QNAME);
    }

    public WebservicehelloService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEHELLOSERVICE_QNAME, features);
    }

    public WebservicehelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebservicehelloService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Webservicehello
     */
    @WebEndpoint(name = "WebservicehelloPort")
    public Webservicehello getWebservicehelloPort() {
        return super.getPort(new QName("http://ws.helloweb.com/", "WebservicehelloPort"), Webservicehello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Webservicehello
     */
    @WebEndpoint(name = "WebservicehelloPort")
    public Webservicehello getWebservicehelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.helloweb.com/", "WebservicehelloPort"), Webservicehello.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEHELLOSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEHELLOSERVICE_EXCEPTION;
        }
        return WEBSERVICEHELLOSERVICE_WSDL_LOCATION;
    }

}
